---
output:
  html_document:
    keep_md: true
---

With prospective PhD students coming to visit our department in a week, I thought I would write up some advice on what to look for when visiting a graduate program. Although I only visited biostatistics programs, hopefully some of this advice can be applied to any graduate program visit. There are obviously many things to take into account when choosing a graduate program, but these are things that I believe you can really only find out by visiting a school.

1. Find out if the students are happy. Seriously, go around to students and ask them if they're happy. 99% of them will tell you the truth, and if you're smart enough to get invited to visit a PhD program, you can probably tell if they're lying. However, there is a caveat to this. __Downweight the opinions of students who have not taken their qualifying exams__. The qualifying exam is inherently stressful--if you find someone who is happy with the amount of stress and pressure that comes with a qualifying exam, you should talk to them about life skills rather than graduate school. From my experience as a 1st year student last year, it's difficult to step back and appreciate the problem solving skills you learn by working through the problems you're expected to solve to pass the qualifying exam. I think it's more valuable talking to students in their 3rd and 4th year who have a better perspective to evaluate whether the program provided the appropriate support to get through this challenging time. In addition, these students can tell you about their research experience within the program, which is more representative of what you will be doing for the majority of your time in graduate school.

2. Make sure you see all of the facilities available for the students, especially the student offices. If you know you can't work from home, you will be spending a lot of time in your office. One of the things I really like about Hopkins is the open office space. Other schools had more cubicle like setups for students, which I was not a fan of. If a program has nice student offices, this is also probably reflective of program funding and generally how well the program treats their students.

3. Try to take time to get a feel for the city that the school is in. Like I said earlier, you're going to be living here for at least 4-5 years! Visiting weekends are often jam packed with events, but try to visit at least 1 or 2 neighborhoods where a lot of students live and just walk around. You should feel confident that you're going to enjoy spending time outside of your program/computer.

4. When all is said and done, did you feel at home during the visit? Yes, this is super generic/abstract, but you probably did the same thing for deciding which undergraduate program to attend. Don't worry too much about the students that you tour with, since not all of them are going to the school you choose. Instead, see if you get along with the students that are already in the program. In addition, you will be able to see how the students and professors interact. One of the things I love about Hopkins is how close knit the department is, but that's not something that everyone value.

Hopefully this was helpful for those of you who have visited/are visiting graduate programs! If you have any of your own advice, let me know in the comments, and I'd be happy to add it to the post.
